
create type user_role_enum as enum (
    'ADMIN',
    'USER'
);

create type user_status_enum as enum (
    'ACTIVE',
    'PENDING_VERIFICATION',
    'BANNED'
);

create table if not exists user_account (
    id uuid primary key,
    username varchar(32) not null unique,
    email varchar(256) not null unique,
    password varchar(128) not null,
    user_role user_role_enum not null,
    user_status user_status_enum not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table if not exists email_verify_token (
    id uuid primary key,
    user_account_id uuid not null,
    token varchar(128) not null unique,
    expires_at timestamp not null,
    used boolean not null default false,
    created_at timestamp not null,
    foreign key (user_account_id) references user_account(id) on delete cascade
);


create table if not exists password_reset (
    id uuid primary key,
    user_account_id uuid not null,
    token varchar(128),
    expires_at timestamp,
    used boolean,
    created_at timestamp not null,
    foreign key (user_account_id) references user_account(id) on delete cascade
);

create type media_type_enum as enum (
    'LOGO',
    'PROFILE',
    'POSTER',
    'PHOTO',
    'TRAILER',
    'BACKDROP',
    'BANNER',
    'TEASER',
    'FEATURETTE',
    'CLIP',
    'BLOOPER',
    'INTERVIEW',
    'AVATAR'
);

create table if not exists media (
    id uuid primary key,
    url varchar(256) not null,
    media_type media_type_enum not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table if not exists country (
    id int primary key,
    name varchar(128) not null unique
);

create table if not exists user_detail (
    user_id uuid primary key,
    description text,
    country_id int,
    created_at timestamp not null,
    updated_at timestamp not null,
    foreign key (user_id) references user_account(id) on delete cascade,
    foreign key (country_id) references country(id) on delete set null
);

create table if not exists user_essential_media (
    user_id uuid primary key,
    avatar_id uuid,
    backdrop_id uuid,
    foreign key (user_id) references user_detail(user_id) on delete cascade,
    foreign key (avatar_id) references media(id) on delete set null,
    foreign key (backdrop_id) references media(id) on delete set null
);

create table if not exists user_following (
    follower_user_id uuid,
    followed_user_id uuid,
    primary key (follower_user_id, followed_user_id),
    foreign key (follower_user_id) references user_detail(user_id) on delete cascade,
    foreign key (followed_user_id) references user_detail(user_id) on delete cascade
);


insert into country (id, name)
values
    (1, 'United States of America'),
    (2, 'Afghanistan'),
    (3, 'Albania'),
    (4, 'Algeria'),
    (5, 'Andorra'),
    (6, 'Angola'),
    (7, 'Antigua & Deps'),
    (8, 'Argentina'),
    (9, 'Armenia'),
    (10, 'Australia'),
    (11, 'Austria'),
    (12, 'Azerbaijan'),
    (13, 'Bahamas'),
    (14, 'Bahrain'),
    (15, 'Bangladesh'),
    (16, 'Barbados'),
    (17, 'Belarus'),
    (18, 'Belgium'),
    (19, 'Belize'),
    (20, 'Benin'),
    (21, 'Bhutan'),
    (22, 'Bolivia'),
    (23, 'Bosnia Herzegovina'),
    (24, 'Botswana'),
    (25, 'Brazil'),
    (26, 'Brunei'),
    (27, 'Bulgaria'),
    (28, 'Burkina'),
    (29, 'Burma'),
    (30, 'Burundi'),
    (31, 'Cambodia'),
    (32, 'Cameroon'),
    (33, 'Canada'),
    (34, 'Cape Verde'),
    (35, 'Central African Rep'),
    (36, 'Chad'),
    (37, 'Chile'),
    (38, 'Republic of China'),
    (39, 'Colombia'),
    (40, 'Comoros'),
    (41, 'Democratic Republic of the Congo'),
    (42, 'Republic of the Congo'),
    (43, 'Costa Rica'),
    (44, 'Croatia'),
    (45, 'Cuba'),
    (46, 'Cyprus'),
    (47, 'Czech Republic'),
    (48, 'Danzig'),
    (49, 'Denmark'),
    (50, 'Djibouti'),
    (51, 'Dominica'),
    (52, 'Dominican Republic'),
    (53, 'East Timor'),
    (54, 'Ecuador'),
    (55, 'Egypt'),
    (56, 'El Salvador'),
    (57, 'Equatorial Guinea'),
    (58, 'Eritrea'),
    (59, 'Estonia'),
    (60, 'Ethiopia'),
    (61, 'Fiji'),
    (62, 'Finland'),
    (63, 'France'),
    (64, 'Gabon'),
    (65, 'Gaza Strip'),
    (66, 'The Gambia'),
    (67, 'Georgia'),
    (68, 'Germany'),
    (69, 'Ghana'),
    (70, 'Greece'),
    (71, 'Grenada'),
    (72, 'Guatemala'),
    (73, 'Guinea'),
    (74, 'Guinea-Bissau'),
    (75, 'Guyana'),
    (76, 'Haiti'),
    (77, 'Holy Roman Empire'),
    (78, 'Honduras'),
    (79, 'Hungary'),
    (80, 'Iceland'),
    (81, 'India'),
    (82, 'Indonesia'),
    (83, 'Iran'),
    (84, 'Iraq'),
    (85, 'Republic of Ireland'),
    (86, 'Israel'),
    (87, 'Italy'),
    (88, 'Ivory Coast'),
    (89, 'Jamaica'),
    (90, 'Japan'),
    (91, 'Jonathanland'),
    (92, 'Jordan'),
    (93, 'Kazakhstan'),
    (94, 'Kenya'),
    (95, 'Kiribati'),
    (96, 'North Korea'),
    (97, 'South Korea'),
    (98, 'Kosovo'),
    (99, 'Kuwait'),
    (100, 'Kyrgyzstan'),
    (101, 'Laos'),
    (102, 'Latvia'),
    (103, 'Lebanon'),
    (104, 'Lesotho'),
    (105, 'Liberia'),
    (106, 'Libya'),
    (107, 'Liechtenstein'),
    (108, 'Lithuania'),
    (109, 'Luxembourg'),
    (110, 'Macedonia'),
    (111, 'Madagascar'),
    (112, 'Malawi'),
    (113, 'Malaysia'),
    (114, 'Maldives'),
    (115, 'Mali'),
    (116, 'Malta'),
    (117, 'Marshall Islands'),
    (118, 'Mauritania'),
    (119, 'Mauritius'),
    (120, 'Mexico'),
    (121, 'Micronesia'),
    (122, 'Moldova'),
    (123, 'Monaco'),
    (124, 'Mongolia'),
    (125, 'Montenegro'),
    (126, 'Morocco'),
    (127, 'Mount Athos'),
    (128, 'Mozambique'),
    (129, 'Namibia'),
    (130, 'Nauru'),
    (131, 'Nepal'),
    (132, 'Newfoundland'),
    (133, 'Netherlands'),
    (134, 'New Zealand'),
    (135, 'Nicaragua'),
    (136, 'Niger'),
    (137, 'Nigeria'),
    (138, 'Norway'),
    (139, 'Oman'),
    (140, 'Ottoman Empire'),
    (141, 'Pakistan'),
    (142, 'Palau'),
    (143, 'Panama'),
    (144, 'Papua New Guinea'),
    (145, 'Paraguay'),
    (146, 'Peru'),
    (147, 'Philippines'),
    (148, 'Poland'),
    (149, 'Portugal'),
    (150, 'Prussia'),
    (151, 'Qatar'),
    (152, 'Romania'),
    (153, 'Rome'),
    (154, 'Russian Federation'),
    (155, 'Rwanda'),
    (156, 'Grenadines'),
    (157, 'Samoa'),
    (158, 'San Marino'),
    (159, 'Sao Tome & Principe'),
    (160, 'Saudi Arabia'),
    (161, 'Senegal'),
    (162, 'Serbia'),
    (163, 'Seychelles'),
    (164, 'Sierra Leone'),
    (165, 'Singapore'),
    (166, 'Slovakia'),
    (167, 'Slovenia'),
    (168, 'Solomon Islands'),
    (169, 'Somalia'),
    (170, 'South Africa'),
    (171, 'Spain'),
    (172, 'Sri Lanka'),
    (173, 'Sudan'),
    (174, 'Suriname'),
    (175, 'Swaziland'),
    (176, 'Sweden'),
    (177, 'Switzerland'),
    (178, 'Syria'),
    (179, 'Tajikistan'),
    (180, 'Tanzania'),
    (181, 'Thailand'),
    (182, 'Togo'),
    (183, 'Tonga'),
    (184, 'Trinidad & Tobago'),
    (185, 'Tunisia'),
    (186, 'Turkey'),
    (187, 'Turkmenistan'),
    (188, 'Tuvalu'),
    (189, 'Uganda'),
    (190, 'Ukraine'),
    (191, 'United Arab Emirates'),
    (192, 'United Kingdom'),
    (193, 'Uruguay'),
    (194, 'Uzbekistan'),
    (195, 'Vanuatu'),
    (196, 'Vatican City'),
    (197, 'Venezuela'),
    (198, 'Vietnam'),
    (199, 'Yemen'),
    (200, 'Zambia'),
    (201, 'Zimbabwe');
